### ISSUE TITLE
consensus failure

### ISSUE THREAD

**Issue by faddat** [faddat/dig#46]
10:59PM ERR CONSENSUS FAILURE!!! err="+2/3 committed an invalid block: wrong Block.Header.AppHash.  Expected BD6F680E4EC85B7433B40BE64D10ECDECF75165A42C820735F78197ADCE00A09, got 84F934020D77CA68EF49ADC994A9B283DA9E07113E25FDBF6D5C04EA1EEDA15D" module=consensus stack="goroutine 308 [running]:\nruntime/debug.Stack(0xc0005f0d30, 0x1b0db40, 0xc0012e0020)\n\t/usr/lib/go/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2(0xc000233500, 0x205b5e8)\n\t/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/consensus/state.go:726 +0x5b\npanic(0x1b0db40, 0xc0012e0020)\n\t/usr/lib/go/src/runtime/panic.go:965 +0x1b9\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc000233500, 0x2)\n\t/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/consensus/state.go:1575 +0x1385\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc000233500, 0x2)\n\t/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/consensus/state.go:1546 +0x428\ngithub.com/tendermint/tendermint/consensus.(*State).addProposalBlockPart(0xc000233500, 0xc00062bf50, 0xc000524270, 0x28, 0xc001a90600, 0xc001a90900, 0xc03e29872ae51301)\n\t/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/consensus/state.go:1919 +0x7c5\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc000233500, 0x223be60, 0xc00062bf50, 0xc000524270, 0x28)\n\t/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/consensus/state.go:820 +0x5cc\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc000233500, 0x0)\n\t/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/consensus/state.go:762 +0x3f2\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\t/root/go/pkg/mod/github.com/tendermint/tendermint@v0.34.11/consensus/state.go:378 +0x8c5\n"

q: is this because of versioning, or is it something deeper?

**Comment by faddat** [comment]
ha!

Versioning.  Cosmos-SDK 0.42.8 was sneaking in through spm.

Solution: replace that spm with mine, which is upgraded to 0.43.0
